
spring:
  r2dbc:
    url: r2dbc:h2:mem:///accountdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

  h2:
    console:
      enabled: true

  sql:
    init:
      mode: always
server:
  port: 8081
